## numpy와 닮은 pytorch

In [1]:
import torch

In [10]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.shape)

b = torch.tensor([1, 2, 3, 4.]) # 하나라도 실수라면..?
print(b)
print(b.dtype) # 자동으로 전체 실수 타입으로..!

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.Size([4])
tensor([1., 2., 3., 4.])
torch.float32


In [18]:
A = torch.tensor([[1, 2, 3], [3, 4, 5]])
print(A)

'''
리스트와 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야한다.. 즉 열의 개수가 같아야함
'''

print(A.shape) # 2x3
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수 ==> 텐서의 원소 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [19]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [20]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [21]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product, element-wise product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [22]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 행렬 곱

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## 인덱싱 & 슬라이싱

In [ ]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7]) # 처음부터 즉 0부터 7번째 전까지
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([ [1,2,3], [4,5,6], [7,8,9] ])
print(A[0]) # 0번째 행
print(A[-1]) # 마지막 행
print(A[:-1])
print(A[0][2]) # 0번쨰 행의 2번째 원소 -> 3
print(A[0, 2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor(3)
tensor(3)


In [ ]:
# 3차원 행렬
A = torch.tensor([
    [[0,1,2,3], [4,5,6,7], [8,9,10,11]],
    [[12,13,14,15], [16,17,18,19], [20,21,22,23]]
])

print(A)
print(A.shape)
print(A.size())
print(A.ndim) # (채 x 행 x 열)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
3


In [38]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])


In [39]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

tensor([[1, 2],
        [7, 8]])


## Pytorch의 여러 함수들

In [40]:
A=torch.randn(3,3) # Normal 의 n
B=torch.rand(3,3) # 이건 uniform
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[ 1.5897, -0.6294,  1.7805],
        [ 0.1715,  0.3260,  0.7065],
        [ 1.5606,  1.6462, -2.0014]])
tensor([[0.9663, 0.2621, 0.6504],
        [0.6461, 0.5259, 0.9160],
        [0.8685, 0.6969, 0.1307]])
tensor([], size=(0, 3))


In [41]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.7126, -1.2993, -0.3161],
        [-0.7183, -0.8626, -0.4827],
        [ 0.3892, -0.9365, -1.0008]])
tensor([[0.7126, 1.2993, 0.3161],
        [0.7183, 0.8626, 0.4827],
        [0.3892, 0.9365, 1.0008]])
tensor([[0.8442, 1.1399, 0.5622],
        [0.8475, 0.9287, 0.6947],
        [0.6239, 0.9677, 1.0004]])
tensor([[2.0393, 0.2727, 0.7290],
        [0.4876, 0.4221, 0.6171],
        [1.4758, 0.3920, 0.3676]])
tensor([[-3.3883e-01,  2.6180e-01, -1.1517e+00],
        [-3.3092e-01, -1.4785e-01, -7.2844e-01],
        [-9.4367e-01, -6.5590e-02,  7.5538e-04]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[ 1., -1., -0.],
        [-1., -1., -0.],
        [ 0., -1., -1.]])
tensor([[ 0.7100, -1.3000, -0.3200],
        [-0.7200, -0.8600, -0.4800],
        [ 0.3900, -0.9400, -1.0000]])
tensor([[ 0., -2., -1.],
        [-1., -1., -1.],
        [ 0., -1., -2.]])
tensor([[ 1., -1., -0.],
        [-0., -0., -0.],
        [ 1., -0., -1.]])


In [42]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)


torch.Tensor

In [43]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [53]:
A = torch.randn(3, 4)
print(A)
print(torch.max(A))
print(torch.max(A, dim = 0))
"""values =>각 행(dim=0)의 최대값, indices => 각 행에서 최대값의 index"""
print("=" * 30)
print(torch.max(A,dim=1))
print("=" * 30)
print(torch.max(A, dim = 1, keepdim=True)) 

tensor([[ 0.6667, -0.2584,  0.7936,  0.2920],
        [-1.3462, -0.5117, -0.9914, -1.4933],
        [-0.2462,  0.3977, -0.8419, -1.6658]])
tensor(0.7936)
torch.return_types.max(
values=tensor([0.6667, 0.3977, 0.7936, 0.2920]),
indices=tensor([0, 2, 0, 0]))
torch.return_types.max(
values=tensor([ 0.7936, -0.5117,  0.3977]),
indices=tensor([2, 1, 1]))
torch.return_types.max(
values=tensor([[ 0.7936],
        [-0.5117],
        [ 0.3977]]),
indices=tensor([[2],
        [1],
        [1]]))


In [54]:
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([0, 2, 0, 0])
tensor([2, 1, 1])


In [55]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-0.2839,  1.0094, -0.8917, -0.4982],
        [-0.7116,  1.0916,  0.3788, -0.3657],
        [ 0.9858, -0.5500,  1.4058, -0.1061]])
tensor(1.4643)
tensor([-0.6645,  0.3932,  1.7356])
tensor([[-0.6645],
        [ 0.3932],
        [ 1.7356]])
tensor(0.1220)
tensor([-0.1661,  0.0983,  0.4339])
tensor([[-0.1661],
        [ 0.0983],
        [ 0.4339]])
tensor(0.8091)
tensor([[-0.6645],
        [ 0.3932],
        [ 1.7356]])
tensor([[-0.1661],
        [ 0.0983],
        [ 0.4339]])
tensor(0.8091)


In [ ]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

In [ ]:
A = torch.randint(1, 5, size = (2, 3, 4)) # size -> (채 x 행 x 열)
print(A)

tensor([[[2, 1, 2, 4],
         [4, 2, 4, 1],
         [3, 3, 1, 1]],

        [[4, 2, 1, 3],
         [3, 4, 4, 2],
         [1, 1, 3, 2]]])


In [57]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [58]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [60]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다.

E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

print(C)
print(D)
print(E)
print(F)
print(G)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [ ]:
# sqeeze vs unsqeeze
A = torch.randn(1, 1, 1, 3, 1, 1, 4, 1)
print(A.shape)
print(A.squeeze().shape) # 1인 차원 모두 제거!

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [12]:
# unsqeeze -> 차원을 추가! 오직 1차원만!! 더 추가하고 싶다면 view나 shape 사용하자
A = torch.randn(3, 4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [14]:
A = torch.ones(3, 4)
B = torch.zeros(3, 4)

A = A.unsqueeze(dim = 0)
B = B.unsqueeze(dim = 0)
C = torch.cat([A, B], dim = 0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


## Autograd

In [1]:
import torch

In [62]:
x = torch.tensor([1.], requires_grad=True) # requires_grad -> 이 놈을 미분할거야! 라고 알려주는거
# requires_grad = True 할거면 무조건 tensor는 float형으로
print(x)
print(x.requires_grad)

tensor([1.], requires_grad=True)
True


In [ ]:
y = x**2
print(y) # PowBackward가 붙어있다.

# y를 미분해보자
y.backward() 
print(y)

# y=x**2을 미분한 2x의 x값에 1을 대입한 gradient 값
print(x.grad)

tensor([1.], grad_fn=<PowBackward0>)
tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2

print(y)

z = 3*y

print(z) # MulBackward가 붙어있다!

z.backward()

'''
dz/dx = dz/dy * dy/dx = 3 * 2x = 6
'''

print(x.grad) # by chain rule , requires_grad = True인 놈을 대해서 미분 즉! x에 대해서 미분
# print(y.grad) # warning! 중간건 안된다

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [14]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
z=3*y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감
print(x.grad)

tensor([2.])


In [15]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙어있다!
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [64]:
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([1.], requires_grad=True)
z = 2*x**2 + y**2
print(z)

tensor([3.], grad_fn=<AddBackward0>)


In [ ]:
z.backward()
print(x.grad) # z를 x에 대해서 미분
print(y.grad) # z를 y에 대해서 미분
# -> 편미분 느낌

In [65]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [71]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
torch.sum(x)

tensor(6., grad_fn=<SumBackward0>)

In [72]:
y = torch.sum(x**2) # x1**2 + x2**2 + x3**2
print(y)

tensor(14., grad_fn=<SumBackward0>)


In [73]:
y.backward() 
print(x.grad)
"""
[dy/dx1, dy/dx2, dy/dx3]
y = x1^2 + x2^2 + x3^2 이니깐 by sum()
"""

tensor([2., 4., 6.])


'\n[dy/dx1, dy/dx2, dy/dx3]\ny = x1^2 + x2^2 + x3^2 이니깐 by sum()\n'

In [74]:
"""Transfer learning 할 때 필요!!"""
x = torch.tensor([1.], requires_grad=True)
x.requires_grad = False
y=x**2
print(y)
# y.backward() # error!

'''transfer learning?? : 이미 학습된 모델(pre-trained model)을 이용해서 다른 과정 학습'''

tensor([1.])


'transfer learning?? : 이미 학습된 모델(pre-trained model)을 이용해서 다른 과정 학습'

```python
model = models.resnet18(pretrained=True)

# 2. 기존 레이어는 얼리기 (학습 X, gradient 계산 X)
for param in model.parameters():
    param.requires_grad = False  # ← 여기!!

# 3. 마지막 레이어만 우리 task에 맞게 교체
# resnet18의 마지막 fc layer: (512 → 1000) 을
# (512 → 2) 로 교체 (예: 정상 vs 이상 분류)
model.fc = nn.Linear(512, 2)
# 새로 만든 fc layer는 requires_grad=True가 default!

# 4. 학습 시 새 레이어만 업데이트됨
optimizer = torch.optim.Adam(model.fc.parameters())
```

In [ ]:
x=torch.tensor([2.] ,requires_grad=True)
x=x.detach() # detach도 많이 쓰이는 듯 when transfer learning
print(x)
y=x**2
print(y)

In [76]:
# detech와 torch.no_grad
x = torch.tensor([1.], requires_grad=True)
'''최저의 Loss function 값을 찾기 위해서 back-prop을 통해 계산을 하는데
back-prop을 하기 위하선 tensor에 requires_grad를 해줘야함.
근데 이게 메모리를 잡아먹기 때문에 모델 테스트 할시에는 torch.no_grad로 메모리 save'''

with torch.no_grad(): # 이 구문 안에서만 grad 계산x하겠다.
    y = x ** 2
    print(x.requires_grad)
    print(y) # <grad_fn=<PowBackward0>이 없는걸 확인할수 있다
    
print("-" * 20, "with grad", "-"*20)    
print(x.requires_grad)
# y.backward() # error !!!!
y = x ** 2
y.backward()
print(y)
print(x.grad)

True
tensor([1.])
-------------------- with grad --------------------
True
tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y) # <grad_fn=<PowBackward0>이 없는걸 확인할수 있다
# y.backward() # error!

False
tensor([1.])
